// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuwn3a0trR5-SioeYg8n_2eUhFn2ZHQvA',
    appId: '1:439399746037:web:d041206a231a13295b38bc',
    messagingSenderId: '439399746037',
    projectId: 'kantinku-project',
    authDomain: 'kantinku-project.firebaseapp.com',
    storageBucket: 'kantinku-project.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDf7sVPyKIoKS1HdOFjngD1AKzs-oluoUE',
    appId: '1:439399746037:android:593bcb69a57ed2d35b38bc',
    messagingSenderId: '439399746037',
    projectId: 'kantinku-project',
    storageBucket: 'kantinku-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChQstum-JYvB7Jkq5kmLFZZlIw7JYYI-k',
    appId: '1:439399746037:ios:e6cd4de704e452d65b38bc',
    messagingSenderId: '439399746037',
    projectId: 'kantinku-project',
    storageBucket: 'kantinku-project.firebasestorage.app',
    iosBundleId: 'com.example.belajarfirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChQstum-JYvB7Jkq5kmLFZZlIw7JYYI-k',
    appId: '1:439399746037:ios:e6cd4de704e452d65b38bc',
    messagingSenderId: '439399746037',
    projectId: 'kantinku-project',
    storageBucket: 'kantinku-project.firebasestorage.app',
    iosBundleId: 'com.example.belajarfirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAuwn3a0trR5-SioeYg8n_2eUhFn2ZHQvA',
    appId: '1:439399746037:web:31175fcd8d6adbfe5b38bc',
    messagingSenderId: '439399746037',
    projectId: 'kantinku-project',
    authDomain: 'kantinku-project.firebaseapp.com',
    storageBucket: 'kantinku-project.firebasestorage.app',
  );
}
