// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVD3l74MlqYz3SgjMkr4ADAknapNeRZbs',
    appId: '1:478173913017:android:3be5fa942eee8d617ea068',
    messagingSenderId: '478173913017',
    projectId: 'belajarauth-80153',
    databaseURL: 'https://belajarauth-80153-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'belajarauth-80153.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWr7ZXO0XLaSMTYcLW_F3hZOb6wYzKU2M',
    appId: '1:478173913017:ios:afc6f67ec9c94dce7ea068',
    messagingSenderId: '478173913017',
    projectId: 'belajarauth-80153',
    databaseURL: 'https://belajarauth-80153-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'belajarauth-80153.firebasestorage.app',
    androidClientId: '478173913017-pffgl3m3sd9h45a53nf2fq687q5cch46.apps.googleusercontent.com',
    iosClientId: '478173913017-c9oq249h45css21ava6nqjl6904ob1bk.apps.googleusercontent.com',
    iosBundleId: 'com.example.belajarfirebase',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtsbzM4OoTtU8VKd00d7kQ9sb20It_mxA',
    appId: '1:478173913017:web:b81f103a346b635f7ea068',
    messagingSenderId: '478173913017',
    projectId: 'belajarauth-80153',
    authDomain: 'belajarauth-80153.firebaseapp.com',
    databaseURL: 'https://belajarauth-80153-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'belajarauth-80153.firebasestorage.app',
    measurementId: 'G-MGE4P5B0NR',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWr7ZXO0XLaSMTYcLW_F3hZOb6wYzKU2M',
    appId: '1:478173913017:ios:afc6f67ec9c94dce7ea068',
    messagingSenderId: '478173913017',
    projectId: 'belajarauth-80153',
    databaseURL: 'https://belajarauth-80153-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'belajarauth-80153.firebasestorage.app',
    androidClientId: '478173913017-pffgl3m3sd9h45a53nf2fq687q5cch46.apps.googleusercontent.com',
    iosClientId: '478173913017-c9oq249h45css21ava6nqjl6904ob1bk.apps.googleusercontent.com',
    iosBundleId: 'com.example.belajarfirebase',
  );

}